pipeline{
    agent {label 'master'}

    stages{
        stage('Test') {
            steps {
                build(job: 'pre-prod_vm3')
            }
        }
        stage('Pre-Prod') {
            steps {
                build(job: 'Another Pipeline')
            }
        }
    }
}